### ISSUE TITLE
Repository Documentation Tracker

### ISSUE THREAD

**Issue by ShungFei** [SOFTENG310-G7/degree-planner#3]
We need the following documentation in our repository

- [x] Brief project description (include your team name and a note that this project is associated with the University of Auckland SOFTENG 310)
- [X] License
- [x] Code of Conduct
- [X] README
- [x] Contributor guidelines
- [x] Bug report and feature request templates
- [x] Initial list of tasks (documented as issues)
- [x] Wiki

**Comment by cyoo934** [comment]
All documentation is complete! The WIKI could be consistently modified by the contributors in the future, as they add additional functionality.

**Comment by cyoo934** [comment]
All documentation is complete! The WIKI could be consistently modified by the contributors in the future, as they add additional functionality.
